### ISSUE TITLE
redirect-user-back action is no longer firing after successful login

### ISSUE THREAD

**Issue by pdotnet** [oidc-wp/openid-connect-generic#233] opened 2020-09-11 16:23 UTC
I have a site that was set up in January of this year and has been working until recently.  Authentication is still working.  New users from our OAuth provider are still getting logins created.  But role permissions are not being set.

I'm using filter '**openid-connect-generic-user-login-test**' to perform membership tests against the claim.  And then using the action '**openid-connect-generic-redirect-user-back**' to alter the user's wordpress role based on the claim results.  

By sprinkling in error_log() text I was able to determine that the **user-login-test** filter is running correctly.  But the code never makes it into the **redirect-user-back** function at all.  I've confirmed "Redirect Back to Origin Page" is checked in the configuration as per the wiki.

There's nothing unique about this implementation, the filter and action functions are in the functions.php code of the theme, I just can't figure out how to determine why the redirect-user-back action function is not being called even though everything else regarding the authentication process seems to be working.

Wordpress version:  5.5.1
OpenID Connect Generic version:  3.7.1

I know there is an update available but this used to work fine on the current version, so wanted to raise the question first before updating.  Thanks!

**Comment by timnolte** [comment] 2020-09-15 20:56
@pdotnet sorry for the delay in responding to the issue. Can you confirm if this issue exists with version 3.6.0 of the plugin? There were some enhancements related to login redirection in 3.7.x and this may have unknowingly introduced and bug.

**Comment by timnolte** [comment] 2020-09-15 20:59
@pdotnet also did this issue start happening after the update to WordPress 5.5.x? There were a lot of sites that started having issues due to some of the changes in WP 5.5. Our plugin doesn't make use of jQuery so that shouldn't have caused a problem for out plugin directly. There should be a cookie(`openid-connect-generic-redirect`) set in the users browser that is used when the user returns to the site to know where to redirect the user after logging in.

**Comment by pdotnet** [comment] 2020-09-18 18:59
Thanks for your reply.  I'm guessing this happened when our WordPress site got updated to 5.5.1 because that's really the only thing that's changed in our environment other than adding usual content.  I only started using the OpenID Connect Generic plugin starting from version 3.7.1 so I can't comment on 3.6.0.  Are you suggestion I roll back to 3.6.0?  I'm open to try it, but would need assistance on how to install the older version.    

So I just tried logging in to our site with Chrome Dev Tools open, and under cookies I do not see a redirect cookie like you indicated when I am returned back to the site from our authentication provider.  However, when I manually navigate to our site's /wp-admin back-end login page, the "openid-connect-generic-redirect" cookie **does** show up in the cookies list.

**Comment by timnolte** [comment] 2020-09-18 20:47
@pdotnet I would try to downgrade your site to WordPress 5.4.2 and see if the problem goes away. We haven't completed testing with WordPress 5.5.x to confirm 100% compatibility.

**Comment by pdotnet** [comment] 2020-09-23 18:41
@timnolte I looked into it and unfortunately this isn't possible due to our site being a "managed" Wordpress hosted site.  We can't control when they install updates either.  I realize this isn't ideal when having such important plugin dependencies but it's the situation we're in, at least for the time being.  

Is there any other action I can hook into and do the redirect logic in there?  For example 'generic-redirect' documentation says it's the last action method to fire.  Well what's the second-last?  Perhaps I can hook up to that and put my redirect logic in there.

Thanks!

**Comment by timnolte** [comment] 2020-09-23 20:37
@pdotnet if you are going to redirect the user to a static place then yes you can use the `openid-connect-generic-redirect-user-back` action hook to take the user to where you want them to go. If you truly want the user to go back where they originally started there is no way to do this without the cookie being set as that is the only place that location is stored.

**Comment by pdotnet** [comment] 2020-09-23 21:04
@timnolte Yes it's a static location I'm redirecting to, one of two possibilities depending on a value in the claim response.
However the original issue above is that `openid-connect-generic-redirect-user-back` action is no longer firing.  That's what I was doing before it stopped working and led me here.  

So I'm wondering if there is an alternative approach.  What is the action / filter that gets raised _just before_ `openid-connect-generic-redirect-user-back`, and would I be able to do the same manual redirection logic in there for the time being?

**Comment by timnolte** [comment] 2020-09-24 11:19
@pdotnet you should be able to use the `openid-connect-generic-user-logged-in` as it fires right before the redirect user hook. Taking a quick look at the code and I can see where the redirect hook is only able to fire if there was a redirect URL provided from the cookie specifically.

There has been some issues in the past with the cookie-based approach to managing the redirect URL. There is a suggested approach with the OpenID spec to encode this redirect URL into the state when sending it to the IDP, since the IDP sends back the state this would prove to be more reliable than the cookie-based approach. It's on my radar to look at making that change. Hopefully using the `openid-connect-generic-user-logged-in` hook will work for you for the time being.

**Comment by ganthen** [comment] 2021-02-25 08:15
Hey guys, is there an update on this?
This is causing issues on my site as well for already some months. I got that working with downgrading the plugin back to version 3.6.0 some time ago, but today even that doesn't do the trick anymore. The plugin is not capable of writing any cookie value.
Everythiing is on the latest version on my side, I tested this with 3.8.1 as well as 3.6.0 (current version as for now) but no difference.

I would really appreciate some help here. I do want people to be able to log on using our own Identity Server, and get redirected back to the original page, so no static routing in my case. But everyone just gets back to the home page instead of the original post.

**Comment by timnolte** [comment] 2021-02-25 11:33
@ganthen hmm, this sure seems to be something to do more with your site hosting or a conflict with another plugin, however it's still possible there could be something in conflict with WordPress 5.5.x. I've been testing the plugin with WordPress 5.5.x & 5.6.x with at least 3 different IDPs and haven't seen this issue, with the standard plugin settings.

Can you provide all of your site details including:

1. WordPress Version: 
2. PHP Version: 
3. Identity Provider: 
4. WordPress Site Hosting Provider: 
5. Describe the current user flow process that is implemented on your site.
6. All example OIDC plugin hooks code being use on the site.

**Comment by ganthen** [comment] 2021-02-26 12:25
After spending quite some time testing, searching for that solution again, checking on version 3.6.0 and 3.8.1 as well, here are some observations:
- First time visit on the page : no cookie is set
- After logging in, and then logging out, and logging in again : suddenly the cookie is there. So first time visit issue
- I made a change to the forms.php page to get things working all the time. The change on version 3.8.1 is the following:
Adding to the hyperlink tag on line 184: onclick="setRedirectUri()"

Adding a piece of code as a Astra dynamic content part (placed in wp_head):

<script>
// In case of cookie and redirect issues with OpenId Connect General Client, you should add the following to the form.php on line 184:
	//  onclick="setRedirectUri()"
	function setCookie(cname, cvalue, exminutes) {
		var d = new Date();
		d.setTime(d.getTime() + (exminutes*60*60*1000));
		var expires = "expires="+ d.toUTCString();
		document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/;domain=www.cyclingplanner.be";
	}
	
	function setRedirectUri() {
		setCookie('openid-connect-generic-redirect', window.location.href, 30);
	}
	
</script>

By doing so, it all works again. Although it remains an issue each time a new version will be installed as the forms.php will be overwritten.

To get you insights on the environment:

1. WordPress version 5.6.2
2. PHP version 7.4.15
3. Identity provider : IdentityServer4
4. WordPress Site Hosting Provider : SiteGround
5. User flow : regular flow of WooCommerce of someone accessing "My account", getting on a page with a login button if not logged on yet, or seeing the subscriptions, orders, payment info and a log out button in case they are authenticated. However, the next step on the site is have content hidden for non-authenticated users as well. Therefor my requirement to stay at the original page.
6. Only hook I have implemented it the one changing the button text

I'm happy that this is solved for now, but it took too much energy and remains a risk on newer updates as well. So I'm still looking forward for a better solution or other suggestions.

**Comment by timnolte** [comment] 2021-03-20 21:19
@ganthen FYI, others have also reported some failures with the redirection as well(another recent mention here: https://github.com/oidc-wp/openid-connect-generic/discussions/281) and I'm facing a new issue on 1 client site(out of like 30+) is not working. I will be looking at changing how redirection is being handled in the next week. The plan right now is to move away from using cookies to manage the redirect and manage redirects with the State that is passed between WordPress and the IDPs. This should, in theory, provide a much more reliable redirection handling. I will have to take into consideration all of the redirection capabilities in place already, and ensure that a change to using the state doesn't introduce any major regression issues.

**Closed** 2021-04-08 12:06 UTC
Labels: bug

**Comment by timnolte** [comment] 2021-04-09 02:31
@pdotnet a new version of the plugin has been released that should have this fixed. Give it a try and let us know how it's working for you.

**Comment by ganthen** [comment] 2021-04-12 10:41
Hey Tim,

I have installed the latest version, and just did some tests. I saw indeed that the code has changed, which is good news !
However, at first sight this is working fine. Except the following scenario where I still face an issue:

- I go to my WooCommerce page while I'm not logged on yet. I see a message block telling me to log on in order to see my personal orders tied to my account. This is done with a visibility rule in the Elementor plugin (visible for visitors)
- I keep this page open for some minutes. I grab a coffee in the meantime.
- When returning after some minutes, I get back, and click on the login button
- I log on, No problems with this. I get redirected after the logon.
- I end up on an error page : invalid state. After clicking on links for a new attempt, this system tries to log on to the wp-admin, choosing a different authentication provider, which is confusing for my customers, as well as deadly in terms of support.

However, doing everything in one smooth flow (no idle time, or within the timespan of a few minutes) then it all works fine.
I recorded the steps for you in a small video. Hope this helps you. A quick research tells me something on setting an auth0_state cookie, which I cannot find. Don't know if this has something to do with it. Anyway, I hope this rings a bell on your side.

Link to the video: [https://share.cyclingplanner.be/yAuDbpnp](https://share.cyclingplanner.be/yAuDbpnp)

**Comment by timnolte** [comment] 2021-04-12 10:53
@ganthen so this is due to the State expiring. By default the state is only valid for 180 seconds(3 minutes). You can change the "State time limit" to longer in the plugin settings to help mitigate this however that is a security related setting to protect against replay attacks.

**Comment by ganthen** [comment] 2021-04-13 12:58
Thannks, I understand that. 
However, when the state is gone, and the login will fail, can't we catch this event for a proper redirect to a user friendly page telling our visitors should have to refresh the page and try to log on again ? That page could be a simple WP page, but the redirect behavior might be something to catch properly. Do think of any solution here?

**Comment by timnolte** [comment] 2021-04-13 13:46
@ganthen there are hooks you can use to catch this and then you can redirect your users and provide a proper message about the need to login again. The code was just recently changed in order to fix redirect issues and make them more reliable, but it is tightly coupled with the state. I intentionally made the choice to move away from cookies as that appeared to be the root of so many reported issues and it was the cookie not being able to get set.

**Comment by pdotnet** [comment] 2021-04-13 15:29
@timnolte thanks for the update, I'll start testing this out on our staging site shortly.  Many thanks for your work on this!
