### ISSUE TITLE
users being logged out unexpectedly.

### ISSUE THREAD

**Issue by eriksays** [oidc-wp/openid-connect-generic#252] opened 2020-12-14 16:01 UTC
Has anyone had issues where a user is logged out unexpectedly?
This is where the user has already authenticated (using azure ad), is using the admin, and suddenly finds themselves logged out.
Thanks

**Comment by timnolte** [comment] 2021-01-12 15:08
@eriksays so there have been some reports of this, I have it on my list to dig into this today.

**Comment by timnolte** [comment] 2021-01-14 04:50
This is a duplicate of #238

**Closed by timnolte** 2021-01-14 04:50 UTC
Labels: bug, duplicate
