### ISSUE TITLE
fails existing user test

### ISSUE THREAD

**Issue by mmmccain** [oidc-wp/openid-connect-generic#363] opened 2022-01-07 19:46 UTC
When the "Link existing users" is selected and "Create user if does not exist" is not selected, it fails the "identity-not-map-existing-user" even though the user exists. If "Create user if does not exist" is selected, a new user is not created and the test is passed. 

Failed test with "Create user if does not exist" not selected. User cjashley2@protonmail.com is in the WP system. 

![image](https://user-images.githubusercontent.com/97072059/148598193-0830b972-ff3b-42e0-a258-45a05e500176.png)

User cjashley2@protonmail.com is authenticated. Again, the user is currently in the system but only passed the test if "Create user if does not exist" is selected. 

![image](https://user-images.githubusercontent.com/97072059/148598533-13386432-6d57-4079-b76d-57800798dac2.png)

- [X ] I have deactivated other plugins and confirmed this bug occurs when only this plugin is active.
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

**Comment by timnolte** [comment] 2022-01-07 23:43
This is a duplicate of https://github.com/oidc-wp/openid-connect-generic/issues/278

**Closed** 2022-01-07 23:42 UTC
Labels: bug
