### ISSUE TITLE
post_logout_redirect_uri contains dynamic values

### ISSUE THREAD

**Issue by jerryhopper** [oidc-wp/openid-connect-generic#162] opened 2020-01-14 13:30 UTC
im using this plugin in combination with FusionAuth, and i've run into a problem.

The logout fails on FusionAuth, due to the dynamic url variables added to the redirect url.

Ive opened an issue at Fusionauth  https://github.com/FusionAuth/fusionauth-issues/issues/433
But i thought this could also be 'fixed' from the plugin-side.

So the generated redirect uri contains dynamic values which i cant set in the admin backend of FusioAuth.
Also, in the open-id-connect-generic admin there is no option to not include this variable in the redir url.

So, the wordpress plugin logout generates a url like this: 
https://www.wordpress.ext/wp-login.php?loggedout=true**&wp_lang=nl_NL**

Which is passed to FusionAuth, which is not allowed because ive not registered the **&wp_lang=nl_NL** part. ( which is undoable for sites with multiple languages )

**My question:** 
Is it possible to add a option to NOT include wp_lang parameter on the redirect url?

**Comment by timnolte** [comment] 2021-01-12 23:07
Closing as a duplicate of #177

**Closed by timnolte** 2021-01-12 23:07 UTC
Labels: enhancement
