### ISSUE TITLE
Passworded posts and pages corking up?

### ISSUE THREAD

**Issue by ngpi-integrate** [oidc-wp/openid-connect-generic#123] opened 2019-05-07 11:37 UTC
I've noticed that with the plugin installed, password-protected posts and pages trigger the login interface when the password is input, then the page just hops back to where it was before.

Is this expected behavior? Has anyone else experienced this?

**Comment by MelvinHB** [comment] 2019-07-15 13:08
could fix that bay changing the loginpage manually to https://mydomain/wp-login.php
also works with the plugin: https://wordpress.org/plugins/wps-hide-login/

**Comment by timnolte** [comment] 2021-01-12 17:31
This is a duplicate of #105

**Closed by timnolte** 2021-01-12 17:31 UTC
